### PR TITLE
Allow dot and dash in user/group name

### LINKED ISSUE #7: username cannot contain "." or even "-"
`group mention add jujugrrr to @linux` will work
`group mention add juju.grrr to @linux` will not.

Might just be a small change to the regex https://github.com/bhouse/lita-group-mention/blob/master/lib/lita/handlers/group_mention.rb#L8. I'll try to submit a PR

### PR DESCRIPTION
**Pull request by jujugrrr**
Hi @bhouse.
We have `-` and `.` everywhere here. The PR should fix #7

### CODE REVIEW

**Comment by bhouse** [comment]
Thanks for this, and for fixing the tests! :+1:

**Comment by jujugrrr** [comment]
@bhouse you are welcome :smile:

**Comment by jujugrrr** [comment]
Do you think you could release a new version of the Gem ?

**Comment by bhouse** [comment]
just released v1.1.1 with this fix!

**Comment by jujugrrr** [comment]
Cheers!

**Pull request merged**
